### PR TITLE
Handle more parsing cases (int and str formats, additional props: fix #10, #11 and #13)

### LINKED ISSUE #10: Unsupported int-format: `"enum"`
I have many of those:

```json
"type": {
  "readOnly": true,
  "type": "integer",
  "description": "Output only. The type of the bidding strategy.",
  "format": "enum"
},
```

Coming from <https://github.com/googleapis/googleapis/> protobufs converted to OpenAPI.

```ocaml
(* Generated by jsonschema2atd from openapi.json *)
type json <ocaml module="Yojson.Basic" t="t"> = abstract
type int64 = int <ocaml repr="int64">

jsonschema2atd: internal error, uncaught exception:
                Atdgen_runtime.Oj_run.Error("Line 230:\nUnsupported variant \"enum\"")
```

### PR DESCRIPTION
**Pull request by smondet**

### CODE REVIEW

File: lib/generator.ml [hunk 1]
```diff
@@ -2,23 +2,54 @@ open Json_schema_t
...
+  with_doc : bool;
+  protect_against_duplicates : string list ref option;
+  toplevel_types : [ `All | `Only of string list ];
+  avoid_dangling_refs : bool;
+  json_ocaml_type : [ `From | `Module ] * string * string;
+}
+
+let default_state =
+  {
+    with_doc = true;
```
Comment (ixzzd) [inline lib/generator.ml:15]: Not sure it it should be a default value, or at least tests should be adjusted accordingly

File: lib/generator.ml [hunk 2]
```diff
@@ -2,23 +2,54 @@ open Json_schema_t
...
+    protect_against_duplicates = None;
+    toplevel_types = `All;
+    avoid_dangling_refs = false;
+    json_ocaml_type = `Module, "Yojson.Basic", "t";
```
Comment (ixzzd) [inline lib/generator.ml:19]: This is nice 👍

File: bin/main.ml [hunk 3]
```diff
@@ -44,8 +44,42 @@ let input_format_term =
...
+      )
+      $ Arg.(value (flag (info [ "skip-doc" ] ~doc:"Skip documentation annotations.")))
+      $ Arg.(value (flag (info [ "protect-against-duplicates" ] ~doc:"Make sure no duplicate types are generated.")))
+      $ (const (function
+           | [] -> `All
+           | some -> `Only some
+           )
+        $ Arg.(
+            value (opt_all string [] (info [ "only-matching" ] ~docv:"REGEXP" ~doc:"Only output types matching REGEXP."))
+          )
```
Comment (ixzzd) [inline bin/main.ml:67]: I think we need tests for this one

File: lib/generator.ml [hunk 4]
```diff
@@ -200,33 +233,41 @@ and process_object_type ~ancestors schema =
...
-  | Ref ref_, _ -> type_name (get_ref_name ref_)
+  | Obj schema, ([] | [ _ ]) -> process_schema_type state ~ancestors schema
+  | Obj schema, ancestors -> process_nested_schema_type state ~ancestors schema
+  | Ref ref_, _ -> begin
+    match
+      (not state.avoid_dangling_refs)
+      || List.exists (fun (name, _schema) -> String.equal (get_ref_name ref_) name) !input_toplevel_schemas
+    with
+    | true -> type_name (get_ref_name ref_)
+    | false -> Printf.sprintf "json (* %s *)" (String.concat "/" (List.rev ancestors))
```
Comment (ixzzd) [inline lib/generator.ml:250]:
```suggestion
    | false -> sprintf "json (* %s *)" (String.concat "/" (List.rev ancestors))
```
`Printf` is open in this module

File: bin/main.ml [hunk 5]
```diff
@@ -44,8 +44,42 @@ let input_format_term =
...
+        )
+      $ Arg.(value (flag (info [ "avoid-dangling-refs" ] ~doc:"Convert dangling refs to json.")))
+      $ Arg.(
+          let keyword = enum [ "module", `Module; "from", `From ] in
+          value
+            (opt (t3 ~sep:':' keyword string string) Generator.default_state.json_ocaml_type
+               (info [ "json-ocaml-type" ] ~docv:"KEYWORD:MODULE.PATH:TYPE-NAME"
+                  ~doc:"Use an alternate Mod.type for `json`, e.g. from:My_mod.Submod:json_type."
```
Comment (ixzzd) [inline bin/main.ml:75]: This is nice 👍

File: lib/generator.ml [hunk 6]
```diff
@@ -154,44 +185,46 @@ let rec process_schema_type ~ancestors (schema : schema) =
...
   | Some String -> maybe_nullable "string"
   | Some Boolean -> maybe_nullable "bool"
-  | Some Array -> maybe_nullable (process_array_type ~ancestors schema |> String.concat " ")
-  | Some Object -> process_object_type ~ancestors schema
+  | Some Array -> maybe_nullable (process_array_type state ~ancestors schema |> String.concat " ")
+  | Some Object -> process_object_type state ~ancestors schema
   | None ->
     (* fallback to untyped if schema type is not defined *)
-    maybe_nullable "json"
+    Printf.ksprintf maybe_nullable "json (* %s *)" (String.concat "/" (List.rev ancestors))
```
Comment (ixzzd) [inline lib/generator.ml:196]: Not sure about ancestors lists here, for example:
```diff
   type dynamicConfigValue = {
     ~id  <ocaml default="\"\"">: string;
-    ?value : json option;
+    ?value : json (* DynamicConfigValue/value *) option;
   } 
```
Looks like the comment is a bit redundant here. Do you have an example in mind which would illustrate the reason of having this comment?

Comment (smondet) [reply lib/generator.ml]: I've improved the comments but in that case, there is nothing in the JSON to display for `"value"` :)

```json
"DynamicConfigValue": {
  "type": "object",
  "required": [
    "id"
  ],
  "properties": {
    "id": {
      "type": "string",
      "default": ""
    },
    "value": {}
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
},
```

File: bin/main.ml (hunk 3 above)
Comment (smondet) [reply bin/main.ml:67]: Let me know whether I added enough tests :)
